package br.com.wasabisushi.model;
// Generated 18 de nov. de 2022 12:00:04 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "produto")
public class Produto implements java.io.Serializable {

	private Integer idProduto;
	private Categoria categoria;
	private String nome;
	private Float preco;
	private String descricao;
	private byte[] foto;
	private String precoFormatado;
	private Set<ProdutoPedido> produtoPedidos = new HashSet<ProdutoPedido>(0);

	public Produto() {
	}

	public Produto(Categoria categoria, String nome, Float preco, String descricao, byte[] foto, String precoFormatado,
			Set<ProdutoPedido> produtoPedidos) {
		this.categoria = categoria;
		this.nome = nome;
		this.preco = preco;
		this.descricao = descricao;
		this.foto = foto;
		this.precoFormatado = precoFormatado;
		this.produtoPedidos = produtoPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_produto", unique = true, nullable = false)
	public Integer getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(Integer idProduto) {
		this.idProduto = idProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "preco", precision = 12, scale = 0)
	public Float getPreco() {
		return this.preco;
	}

	public void setPreco(Float preco) {
		this.preco = preco;
	}

	@Column(name = "descricao", length = 65535)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Column(name = "preco_formatado")
	public String getPrecoFormatado() {
		return this.precoFormatado;
	}

	public void setPrecoFormatado(String precoFormatado) {
		this.precoFormatado = precoFormatado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<ProdutoPedido> getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set<ProdutoPedido> produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

}
