package br.com.wasabisushi.model;
// Generated 18 de nov. de 2022 12:00:04 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String email;
	private String senha;
	private String nivelAcesso;
	private String permissao;
	private boolean ativo;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Usuario() {
	}

	public Usuario(String email, String senha, String nivelAcesso, boolean ativo) {
		this.email = email;
		this.senha = senha;
		this.nivelAcesso = nivelAcesso;
		this.ativo = ativo;
	}

	public Usuario(String email, String senha, String nivelAcesso, String permissao, boolean ativo,
			Set<Cliente> clientes) {
		this.email = email;
		this.senha = senha;
		this.nivelAcesso = nivelAcesso;
		this.permissao = permissao;
		this.ativo = ativo;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "senha", nullable = false, length = 7)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "nivel_acesso", nullable = false, length = 45)
	public String getNivelAcesso() {
		return this.nivelAcesso;
	}

	public void setNivelAcesso(String nivelAcesso) {
		this.nivelAcesso = nivelAcesso;
	}

	@Column(name = "permissao", length = 45)
	public String getPermissao() {
		return this.permissao;
	}

	public void setPermissao(String permissao) {
		this.permissao = permissao;
	}

	@Column(name = "ativo", nullable = false)
	public boolean isAtivo() {
		return this.ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
