package br.com.wasabisushi.model;
// Generated 12 de nov. de 2022 22:48:09 by Hibernate Tools 4.3.6.Final

import java.text.NumberFormat;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import org.springframework.data.annotation.Transient;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "produto")
public class Produto implements java.io.Serializable {

	private Integer idProduto;
	private Categoria categoria;
	private String nome;
	private Float preco;
	private String descricao;
	@Lob
	private byte[] foto;
	private Set<ProdutoPedido> produtoPedidos = new HashSet<ProdutoPedido>(0);
	
	@Transient
	Locale ptBr = new Locale("pt", "BR");
	
	@Transient
	String precoFormatado;

	public Produto() {
	}

	public Produto(Categoria categoria, String nome, Float preco, String descricao, byte[] foto,
			Set<ProdutoPedido> produtoPedidos) {
		this.categoria = categoria;
		this.nome = nome;
		this.preco = preco;
		this.descricao = descricao;
		this.foto = foto;
		this.produtoPedidos = produtoPedidos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_produto", unique = true, nullable = false)
	public Integer getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(Integer idProduto) {
		this.idProduto = idProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "preco", precision = 12, scale = 0)
	public Float getPreco() {
		return this.preco;
	}

	public void setPreco(Float preco) {
		this.preco = preco;
	}

	@Column(name = "descricao", length = 65535)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getPrecoFormatado() {
		return precoFormatado;
	}

	public void setPrecoFormatado(String precoFormatado) {
		precoFormatado = NumberFormat.getCurrencyInstance(ptBr).format(this.preco);
		this.precoFormatado = precoFormatado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<ProdutoPedido> getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set<ProdutoPedido> produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

}
