package br.com.wasabisushi.model;
// Generated 12 de nov. de 2022 22:48:09 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * ProdutoPedido generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "produto_pedido")
public class ProdutoPedido implements java.io.Serializable {

	private Integer idProdutoPedido;
	private Pedido pedido;
	private Produto produto;
	private Integer quantidade;
	private Float subtotal;

	public ProdutoPedido() {
	}

	public ProdutoPedido(Pedido pedido, Produto produto, Integer quantidade, Float subtotal) {
		this.pedido = pedido;
		this.produto = produto;
		this.quantidade = quantidade;
		this.subtotal = subtotal;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_produto_pedido", unique = true, nullable = false)
	public Integer getIdProdutoPedido() {
		return this.idProdutoPedido;
	}

	public void setIdProdutoPedido(Integer idProdutoPedido) {
		this.idProdutoPedido = idProdutoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "produto")
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "quantidade")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "subtotal", precision = 12, scale = 0)
	public Float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

}
